version: '3.8'
services:
  server:
    build: ./ZipZapServer
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:password@mongo:27017/ZipZap?authSource=admin
    depends_on:
      - mongo

  # client:
  #   build: ./ZipZapClient
  #   ports:
  #     - "5173:5173" # Change this if using another frontend framework (React, Vue, etc.)
  #   depends_on:
  #     - server

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
